<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Immobilier extends \Entities\Immobilier implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getLibelle()
    {
        $this->__load();
        return parent::getLibelle();
    }

    public function setLibelle($libelle)
    {
        $this->__load();
        return parent::setLibelle($libelle);
    }

    public function getType()
    {
        $this->__load();
        return parent::getType();
    }

    public function setType($type)
    {
        $this->__load();
        return parent::setType($type);
    }

    public function getPrix()
    {
        $this->__load();
        return parent::getPrix();
    }

    public function setPrix($prix)
    {
        $this->__load();
        return parent::setPrix($prix);
    }

    public function getNbChambre()
    {
        $this->__load();
        return parent::getNbChambre();
    }

    public function setNbChambre($nbChambre)
    {
        $this->__load();
        return parent::setNbChambre($nbChambre);
    }

    public function getFokotany()
    {
        $this->__load();
        return parent::getFokotany();
    }

    public function setFokotany($fokotany)
    {
        $this->__load();
        return parent::setFokotany($fokotany);
    }

    public function getContrat()
    {
        $this->__load();
        return parent::getContrat();
    }

    public function setContrat($contrat)
    {
        $this->__load();
        return parent::setContrat($contrat);
    }

    public function getCree()
    {
        $this->__load();
        return parent::getCree();
    }

    public function setCree($cree)
    {
        $this->__load();
        return parent::setCree($cree);
    }

    public function getModifie()
    {
        $this->__load();
        return parent::getModifie();
    }

    public function setModifie($modifie)
    {
        $this->__load();
        return parent::setModifie($modifie);
    }

    public function getFiles()
    {
        $this->__load();
        return parent::getFiles();
    }

    public function addFile($file)
    {
        $this->__load();
        return parent::addFile($file);
    }

    public function addFiles(\Doctrine\Common\Collections\ArrayCollection $files)
    {
        $this->__load();
        return parent::addFiles($files);
    }

    public function removeFiles(\Doctrine\Common\Collections\ArrayCollection $files)
    {
        $this->__load();
        return parent::removeFiles($files);
    }

    public function getAmenities()
    {
        $this->__load();
        return parent::getAmenities();
    }

    public function addAmenity($amenity)
    {
        $this->__load();
        return parent::addAmenity($amenity);
    }

    public function addAmenities(\Doctrine\Common\Collections\ArrayCollection $amenities)
    {
        $this->__load();
        return parent::addAmenities($amenities);
    }

    public function removeAmenities(\Doctrine\Common\Collections\ArrayCollection $amenities)
    {
        $this->__load();
        return parent::removeAmenities($amenities);
    }

    public function getContacts()
    {
        $this->__load();
        return parent::getContacts();
    }

    public function addContact($contact)
    {
        $this->__load();
        return parent::addContact($contact);
    }

    public function addContacts(\Doctrine\Common\Collections\ArrayCollection $contacts)
    {
        $this->__load();
        return parent::addContacts($contacts);
    }

    public function removeContacts(\Doctrine\Common\Collections\ArrayCollection $contacts)
    {
        $this->__load();
        return parent::removeContacts($contacts);
    }

    public function getArea()
    {
        $this->__load();
        return parent::getArea();
    }

    public function setArea($area)
    {
        $this->__load();
        return parent::setArea($area);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getAgence()
    {
        $this->__load();
        return parent::getAgence();
    }

    public function setAgence($agence)
    {
        $this->__load();
        return parent::setAgence($agence);
    }

    public function getAdresse()
    {
        $this->__load();
        return parent::getAdresse();
    }

    public function setAdresse($adresse)
    {
        $this->__load();
        return parent::setAdresse($adresse);
    }

    public function getLatitude()
    {
        $this->__load();
        return parent::getLatitude();
    }

    public function setLatitude($latitude)
    {
        $this->__load();
        return parent::setLatitude($latitude);
    }

    public function getLongitude()
    {
        $this->__load();
        return parent::getLongitude();
    }

    public function setLongitude($longitude)
    {
        $this->__load();
        return parent::setLongitude($longitude);
    }

    public function getIsdeleted()
    {
        $this->__load();
        return parent::getIsdeleted();
    }

    public function setIsdeleted($isdeleted)
    {
        $this->__load();
        return parent::setIsdeleted($isdeleted);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'libelle', 'prix', 'nbChambre', 'cree', 'modifie', 'area', 'description', 'adresse', 'latitude', 'longitude', 'isdeleted', 'type', 'fokotany', 'contrat', 'files', 'amenities', 'contacts', 'agence');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}