<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Agence extends \Entities\Agence implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getLibelle()
    {
        $this->__load();
        return parent::getLibelle();
    }

    public function setLibelle($libelle)
    {
        $this->__load();
        return parent::setLibelle($libelle);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getAdresse()
    {
        $this->__load();
        return parent::getAdresse();
    }

    public function setAdresse($adresse)
    {
        $this->__load();
        return parent::setAdresse($adresse);
    }

    public function getAgents()
    {
        $this->__load();
        return parent::getAgents();
    }

    public function addAgent($agent)
    {
        $this->__load();
        return parent::addAgent($agent);
    }

    public function addAgents(\Doctrine\Common\Collections\ArrayCollection $agents)
    {
        $this->__load();
        return parent::addAgents($agents);
    }

    public function removeAgents(\Doctrine\Common\Collections\ArrayCollection $agents)
    {
        $this->__load();
        return parent::removeAgents($agents);
    }

    public function getImmobiliers()
    {
        $this->__load();
        return parent::getImmobiliers();
    }

    public function addImmobilier($immobilier)
    {
        $this->__load();
        return parent::addImmobilier($immobilier);
    }

    public function addImmobiliers(\Doctrine\Common\Collections\ArrayCollection $immobiliers)
    {
        $this->__load();
        return parent::addImmobiliers($immobiliers);
    }

    public function removeImmobiliers(\Doctrine\Common\Collections\ArrayCollection $immobiliers)
    {
        $this->__load();
        return parent::removeImmobiliers($immobiliers);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'libelle', 'description', 'adresse', 'agents', 'immobiliers');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}